# Generated by Django 3.2.4 on 2021-10-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_college', models.CharField(max_length=50)),
            ],
        ),
    ]
